#pragma once

#define SCREEN_WIDTH 1500
#define SCREEN_HEIGHT 800

#define NUMBER_SPRITE_WIDTH 7
#define	NUMBER_SPRITE_HEIGHT 10

#define NUMBER_WIDTH 50
#define NUMBER_HEIGHT 50

#define COIN_SPRITE_WIDTH 32
#define COIN_SPRITE_HEIGHT 32

#define BUTTON_SPRITE_WIDTH 64
#define BUTTON_SPRITE_HEIGHT 32

#define BUTTON_WIDTH 200
#define BUTTON_HEIGHT 100

#define BLOCK_SIZE 100