#pragma once

#define SCREEN_WIDTH 1300
#define SCREEN_HEIGHT 900

#define SPLASH_SCENE_BACKGROUND_FILEPATH "/"

#define NUMBER_SPRITE_WIDTH 7
#define	NUMBER_SPRITE_HEIGHT 10

#define NUMBER_WIDTH 50
#define NUMBER_HEIGHT 50

#define COIN_SPRITE_WIDTH 32
#define COIN_SPRITE_HEIGHT 32

#define BUTTON_SPRITE_WIDTH 64
#define BUTTON_SPRITE_HEIGHT 32

#define BUTTON_WIDTH 200
#define BUTTON_HEIGHT 100